Готовая разметка файлов index.html и catalog.html
htmlacademy-htmlcss/1448725-device-32 pull request #2
Opened 2021-09-27 08:52 UTC by smirnov-alex

2021-09-28 20:02 UTC, vladpovelitsa requested changes
Привет, хорошая работа, видно что ты старался и внимательно отнесся к материалам курса, продолжай в том же духе!
Есть несколько замечаний, они не критичные, но их нужно исправить, чтобы хорошо защитить проект.

P.S. если появились вопросы или возникают сложности - пиши или отправляй заявку на голосовую консультацию, я всегда рад помочь :)

2021-09-28 20:02 UTC, vladpovelitsa commented on catalog.html
> +          </li>
button нужно заменить на тег <a>

2021-09-30 08:13 UTC, smirnov-alex commented on catalog.html
> +          <button class="visually-hidden" type="submit">Отсортировать продукты</button>
Сделал по аналогии с демкой, подразумевается, что мы выбрали одну из опций сортировки и отсортировали по ней. 
`<select class="select-control" id="sorting" name="sorting">
            <option value="popular">Сначала популярное</option>
            <option value="cheap">Сначала дешёвое</option>
            <option value="expensive">Сначала дорогое</option>
          </select>
          <button class="visually-hidden" type="submit">Отсортировать продукты</button>`

2021-09-30 08:47 UTC, smirnov-alex commented on catalog.html
> +          </li>
на тег <a>?

2021-10-02 22:29 UTC, bmatveyka approved these changes
не увидел ошибок, молодец, хорошая работа!

2021-10-02 22:29 UTC, merged